# to rename
service: aws-nodejs


# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource: "arn:aws:dynamodb:*:*:*"

functions:
  hello:
    handler: src/hello.helloHandler
    events:
      - http:
          path: hello
          method: get
          cors: true

resources:
  Resources:
    PartnersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: 'test'
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: user
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

